version: '3'
services:
    rabbitmq:
      image: 'rabbitmq:3-management'
      ports: 
        - '15672:15672'
        - '5672:5672'
      networks:
      - network-example
    localstack:
      image: localstack/localstack:latest
      environment:
        - DEBUG=1
        - SERVICES=s3
        - DATA_DIR=/tmp/localstack/data
      ports:
       - '4566-4583:4566-4583'
       - '8055:8080'
      volumes:
      - './.localstack:/tmp/localstack'
      networks:
      - network-example
    eureka-srv:
      build: eureka-srv/.
      ports: 
      - '8761:8761'
      networks:
      - network-example
    gateway-srv:
      build: gateway/.
      ports: 
        - '8080:8080'
      networks:
      - network-example
      depends_on:
      - eureka-srv
      environment:
      - EUREKA_URI
    song-srv:
      build: song-srv/.
      ports: 
      - '8092:8092'
      depends_on:
      - eureka-srv
      environment:
      - EUREKA_URI
      - RABBITMQ_NAME
      networks:
      - network-example
    resource-srv:
      build: resource-srv/.
      ports: 
        - '8090:8090'
      networks:
      - network-example
      environment:
      - EUREKA_URI
      - RABBITMQ_NAME
      - S3_URL
      depends_on:
      - eureka-srv
      - rabbitmq
      - localstack
    resource-processor-srv:
      build: resource-processor-srv/.
      ports: 
        - '8091:8091'
      networks:
      - network-example
      depends_on:
        - rabbitmq
    config-srv:
      build: config-srv/.
      ports: 
        - '8888:8888'
      networks:
      - network-example
networks:
  network-example:
    driver: bridge
    external: true
