server:
  port: '8888'
spring:
  application:
    name: 'config-srv'
  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eugband/config-repo-sample.git
