server:
  port: 8080
spring:
  application:
    name: 'gateway-srv'
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
