spring:
  application:
    name: 'resource-srv'
  rabbitmq:
    port: '5672'
    host: ${RABBITMQ_NAME:localhost}
    username: guest
    password: guest
    queue:
      create: createq
      delete: deleteq
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    stream:
      overrideCloudConnectors: true
      bindings:
        output-1:
          destination: createq
          group: createq
          contentType: application/json
          binder: rabbit
      rabbit:
        bindings:
          Output-1:
            consumer:
              max-attempts: 3
              autoBindDlq: true
              dlqTtl: 5000
server:
  port: '8090'
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true

cloud:
  aws:
    s3-bucket-name: mp3-bucket
    s3-mp3-folder: mp3
s3:
  access:
    name: localstack
    secret: localstack
  endpoint:
    url: ${S3_URL:http://localhost:4566}
  region:
    name: us-east-1
