spring:
  application:
    name: 'resource-processor-srv'
  rabbitmq:
    port: '5672'
    host: ${RABBITMQ_NAME:localhost}
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    stream:
      bindings:
        output-1:
          destination: changeq
          group: changeq
          contentType: application/json
          binder: rabbit
        sink-in-0:
          destination: createq
          contentType: application/json
          group: createq
          queue-name-group-only: true
          bind-queue: true
          exchange-durable: true
          exchange-type: topic
          binder: rabbit
      rabbit:
        bindings:
          Output-1:
            consumer:
              max-attempts: 3
              autoBindDlq: true
              dlqTtl: 5000
          isink-in-0:
            consumer:
              max-attempts: 3
              autoBindDlq: true
              dlqTtl: 5000
    function:
      definition: sink
server:
  port: '8091'

proxy:
  url: ${PROXY_URL:http://localhost:8080}

resource-service:
  path: '/api/v1/resources/'

song-service:
  path: '/api/v1/songs/'
