spring:
  application:
    name: 'song-srv'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
server:
  port: '8092'
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
