spring:
  application:
    name: 'song-srv'
  rabbitmq:
    port: '5672'
    host: ${RABBITMQ_NAME:localhost}
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
server:
  port: '8092'
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
